# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---

name: üß™ windows-e2e-tests

# This workflow jobs never run. e2e-windows.yaml has the windows e2e workflow which gets executed when PR is added to a merge queue, before merge to main.
# This workflow is created as a workaround, as mentioned in the discussion linked below.
# Merge Group Discussions: https://github.com/orgs/community/discussions/51120
on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  teste2ewindows:
    if: false # https://github.com/orgs/community/discussions/51120
    name: üß™ Run e2e Tests (Windows)
    runs-on: windows-latest
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
